### ISSUE TITLE
Alterar Valor da Captura

### ISSUE THREAD

**Issue by superainovacoes** [DeveloperCielo/API-3.0-FAQ#2]
Temos um cenário em que a compra por exemplo seria de R$ 100,00 porem no processo até o produto ser entregue o valor poderia variar para mais ou para menos (digamos que possa ser o valor da taxa de entrega).
É possível alterar o valor da captura? ou teríamos que cancelar a atual e fazer uma nova captura com o novo valor?

**Comment by netojoaobatista** [comment]
Pode variar quanto? É uma variação muito grande?

**Comment by superainovacoes** [comment]
Temos alguns casos em que pode variar de centavos até milhar.

Depende do cliente, onde ele pode querer continuar a compra por causa de algum produto indisponível.

**Comment by netojoaobatista** [comment]
Centavos é um caso de uso; milhar não é um caso de uso. Não se autoriza uma compra com uma diferença provável de milhar, entrega para o cliente e, aí, descobre-se que o milhar ultrapassa o limite do cartão do cliente. Centavos até é possível resolver; milhar não.

**Comment by superainovacoes** [comment]
Temos um caso que uma compra variou de R$3.890,28 para R$2.182,39
Mas a variação média (quando ocorre) é de R$ 25,00

A API tem esse recurso?
Como podemos proceder?

**Comment by netojoaobatista** [comment]
Enfim, o que você vai fazer é o seguinte:

1. Crie uma autorização com o valor do produto somado à variação média para cima; por exemplo, se o produto custa 100, você autoriza 125.
2. Entregue o produto.
3. Quando tiver o valor final, seja para mais ou para menos, você faz a captura do valor final - 103, ou 80, ou o valor que tenha ficado após a entrega - *dentro, óbvio, dos 25 de margem da sua autorização*.
4. Cancela a diferença.

* Autorização: https://developercielo.github.io/Webservice-3.0/#criando-uma-transação-completa
* Captura: https://developercielo.github.io/Webservice-3.0/#capturando-uma-venda
* Cancelamento: https://developercielo.github.io/Webservice-3.0/#cancelando-uma-venda

Para a autorização com captura posterior, defina a propriedade `capture` como `false`. Tanto para a captura quanto para o cancelamento, utilize o parâmetro `amount` com o valor que será capturado e cancelado.

**Comment by superainovacoes** [comment]
Maravilha, os testes aqui deram certo. Apenas para não ficar duvida:

No retorno do cancelamento só retorna "voided" quando é o cancelamento total, se eu cancelar parcial ele retorna "paymentconfirmed", correto?

Não consegui ver um status diferente de "voided/paymentconfirmed" nos testes de cancelamento parcial, pode ocorrer e caso caso ocorra um problema no cancelamento parcial devo esperar o status "notfinished" ?

Seria interessante na documentação tem os possíveis status que possa ser retornada para cada requisição.
